### ISSUE TITLE
Gives a "Failed to resolve error"!

### ISSUE THREAD

**Issue by imdad15** [zeng1990java/WaveProgressView#1]
Can't sync with gradle.

**Comment by zeng1990java** [comment]
do you add maven { url "https://jitpack.io" } in you project's build.gradle file?

**Comment by imdad15** [comment]
yes i did! didn't worked.. so I simply copied the library and used it. Anyways, thanks for the lib, tried myself to do it few months back but didnt get enough time... this works like a charm!

**Comment by zeng1990java** [comment]
Thank you for using. Have a nice day.
